# Use postgres/example user/password credentials
version: '3.9'

services:

  app:
    image: node
    restart: unless-stopped
    working_dir: /var/www/app
    command: node ./dist/index.js
    volumes:
      - ./dist:/var/www/app/dist
      - ./node_modules:/var/www/app/node_modules
      - ./.env:/var/www/app/.env
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_started

  db:
    image: postgres
    restart: unless-stopped
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_USER: bothub
      POSTGRES_PASSWORD: pg_password
      POSTGRES_DB: bothub
    ports:
      - 5432:5432
      
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080